name=MPU6886
version=1.0.0
author=lfpu
maintainer=lfpu
sentence=Library to control I2C MPU6886
paragraph=Library to control I2C MPU6886
category=Device Control
url=https://github.com/lfpu/MPU6886
architectures=*
includes=MPU6886.h